version: "3.4"

networks:
  agrotis:
    external: false

services:

  agrotis-db:
    image: mysql:8.0
    container_name: agrotis-db
    restart: "always"
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /data/application/init.sql
    networks:
      - agrotis
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/init.sql:/data/application/init.sql